### PR TITLE
Add release notes file option

### PR DESCRIPTION
**Pull request by jongha**

### CODE REVIEW

**Comment by jongha** [comment]
@wzieba Same here. :(
Can you try force merge?

**Comment by wzieba** [comment]
@jongha thanks a lot for recreating PR! Indeed still doesn't pass :(.

I can force merge but I'm afraid that this can break peoples workflows - we don't want this to happen. We have to know why this PR fails.

**Comment by jongha** [comment]
Can you add me as a collaborator? @wzieba 
And I will request a pull request again.

**Comment by wzieba** [comment]
@jongha done! Thanks for helping with that :)

**Comment by jongha** [comment]
I found a error. @wzieba 
Please check "Settings -> Secrets" 
> Secrets are not passed to workflows that are triggered by a pull request from a fork. Learn more.

**Comment by jongha** [comment]
I think this merge is safe because the build was successful on my forked repository.
https://github.com/jongha/Firebase-Distribution-Github-Action/actions/runs/44364540

**Comment by wzieba** [comment]
> Secrets are not passed to workflows that are triggered by a pull request from a fork. Learn more.

Right, I've missed that. Many thanks for pointing this out, it makes totally sense that secrets aren't exposed that easily.

**Comment by wzieba** [comment]
@long1eu fyi thanks to @jongha  we've just merged requested feature. Hope it'll work fine for you!

**Pull request merged**
