### PR TITLE
Add release notes file option

### PR DESCRIPTION
**Pull request by jongha**

### CODE REVIEW

**Comment by jongha** [comment]
Add `pull_request` in `main.yml` but action failed.
Is the secret value (`FIREBASE_APP_ID, FIREBASE_TOKEN`) in setting menu set ?

**Comment by jongha** [comment]
Added `pull_request` in `main.yml` but failed.
Are secret values set in the setting menu?
Firebase token is valid now?

Passed in my forked repo (https://github.com/jongha/Firebase-Distribution-Github-Action/runs/415018664?check_suite_focus=true)

**Comment by wzieba** [comment]
I've updated credentials (`FIREBASE_TOKEN` and `FIREBASE_APP_ID`) but I'm having trouble with restarting Github Actions check

image

Maybe you could `amend` recent commit (to change hash) and force-push to trigger new CI check?

**Comment by jongha** [comment]
I pushed the code again but still got an error.
`Error: Command requires authentication, please run firebase login`

Maybe the firebase token seems to be wrong. What do you think?

**Comment by long1eu** [comment]
I really need this. @wzieba can you help?

**Comment by jongha** [comment]
Please let me know if there is anything that needs to be modified to be merge.

**Comment by wzieba** [comment]
@jongha @long1eu I'm sorry guys, I totally forgot about this PR. I'll prioritise it and check for failing build in next 24 hours maximum. Sorry again!

**Comment by wzieba** [comment]
@jongha I've checked credentials locally and created test PR (https://github.com/wzieba/Firebase-Distribution-Github-Action/pull/7) with current credentials. Both works, but your PR still doesn't pass test.

This error is indeed thrown because of authentication error https://github.com/firebase/firebase-tools/blob/15a582cd2d92ad7477e9364a61bb17a98478fe8e/src/requireAuth.js but I really can't figure out why your PR doesn't pass on this repo (but passes on yours!).

That's really strange and last thing I can think of is... re-create pull request. Maybe something stuck on Github Actions (e.g. I had issue with re-running your PR check).

I think it's crucial to make sure that new code that lands in this repo will work for all users, that's why I would love to merge this PR but with passing test only.

Could you please recreate this Pull request?

**Comment by jongha** [comment]
No Problem, please wait.

**Pull request closed without merging**
